-- ============================================================================
-- CelRevive PostgreSQL DDL - Updated Recommendation Architecture
-- Version: 2.0
-- Date: 2026-08-13
--
-- Purpose
--   Consolidated schema for CelRevive master/reference data, compatibility data,
--   operational formulation data, and the explainable recommendation model:
--
--     skin_concern
--         -> concern_benefit (weighted mapping)
--         -> benefit
--         -> active_benefit_score
--         -> active
--
--   IMPORTANT: Active-to-skin-concern relevance is DERIVED. It is intentionally
--   not maintained as a hard-coded master mapping table.
--
-- Notes
--   1. Existing business IDs are preserved as supplied by CelRevive:
--        active.active_id       = INTEGER (e.g. 1..15)
--        benefit.benefit_id     = INTEGER (e.g. 1..20)
--        skin_concern.concern_id = VARCHAR(10) (e.g. SC0001)
--   2. concern_benefit and active_benefit_score are versioned.
--   3. Weight-sum validation for concern_benefit is enforced by a deferred
--      constraint trigger so each concern/version must total 1.00000.
--   4. The ranking views use the latest available mapping version per concern
--      and the latest active/benefit score version per active-benefit pair.
-- ============================================================================

BEGIN;

-- UUID generation for operational entities.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ============================================================================
-- 1. REFERENCE / MASTER TABLES
-- ============================================================================

CREATE TABLE IF NOT EXISTS supplier (
    supplier_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_name    VARCHAR(255) NOT NULL,
    website          TEXT,
    country          VARCHAR(100),
    contact_email    VARCHAR(320),
    CONSTRAINT uq_supplier_name UNIQUE (supplier_name)
);

CREATE TABLE IF NOT EXISTS primary_category (
    category_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name      VARCHAR(255) NOT NULL,
    ai_matching_notes  TEXT,
    identified_by      TEXT,
    CONSTRAINT uq_primary_category_name UNIQUE (category_name)
);

CREATE TABLE IF NOT EXISTS benefit (
    benefit_id      INTEGER PRIMARY KEY,
    benefit_name    VARCHAR(255) NOT NULL,
    CONSTRAINT uq_benefit_name UNIQUE (benefit_name)
);

COMMENT ON TABLE benefit IS
'CelRevive benefit dimension. IDs correspond to the supplied benefit master list.';

CREATE TABLE IF NOT EXISTS skin_concern (
    concern_id                  VARCHAR(10) PRIMARY KEY,
    concern_name                VARCHAR(255) NOT NULL,
    detectable_by_selfie        BOOLEAN NOT NULL DEFAULT FALSE,
    detectable_by_questionnaire BOOLEAN NOT NULL DEFAULT FALSE,
    description                 TEXT,
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_skin_concern_name UNIQUE (concern_name)
);

COMMENT ON TABLE skin_concern IS
'CelRevive skin-concern master. concern_id values include SC0001, SC1001, SC2001, etc.';

CREATE TABLE IF NOT EXISTS source_document (
    doc_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filename        TEXT NOT NULL,
    doc_type        VARCHAR(100),
    description     TEXT,
    version         VARCHAR(50),
    uploaded_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tag (
    tag_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag_text        VARCHAR(255) NOT NULL,
    tag_type        VARCHAR(100),
    CONSTRAINT uq_tag_text_type UNIQUE (tag_text, tag_type)
);

CREATE TABLE IF NOT EXISTS base (
    base_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    base_name        VARCHAR(255) NOT NULL,
    price_tier       VARCHAR(50),
    age_min          SMALLINT,
    age_max          SMALLINT,
    skin_type        VARCHAR(100),
    moisture         VARCHAR(100),
    ph_min           NUMERIC(4,2),
    ph_max           NUMERIC(4,2),
    description      TEXT,
    CONSTRAINT uq_base_name UNIQUE (base_name),
    CONSTRAINT ck_base_age_min CHECK (age_min IS NULL OR age_min >= 0),
    CONSTRAINT ck_base_age_max CHECK (age_max IS NULL OR age_max >= 0),
    CONSTRAINT ck_base_age_range CHECK (
        age_min IS NULL OR age_max IS NULL OR age_min <= age_max
    ),
    CONSTRAINT ck_base_ph_min CHECK (ph_min IS NULL OR (ph_min >= 0 AND ph_min <= 14)),
    CONSTRAINT ck_base_ph_max CHECK (ph_max IS NULL OR (ph_max >= 0 AND ph_max <= 14)),
    CONSTRAINT ck_base_ph_range CHECK (
        ph_min IS NULL OR ph_max IS NULL OR ph_min <= ph_max
    )
);

-- ============================================================================
-- 2. ACTIVE MASTER
-- ============================================================================

CREATE TABLE IF NOT EXISTS active (
    active_id          INTEGER PRIMARY KEY,
    active_name        VARCHAR(255) NOT NULL,
    supplier_id        BIGINT REFERENCES supplier(supplier_id),
    category_id        BIGINT REFERENCES primary_category(category_id),
    cost_per_gram      NUMERIC(12,4),
    usage_level_min    NUMERIC(8,4),
    usage_level_max    NUMERIC(8,4),
    description        TEXT,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_active_name UNIQUE (active_name),
    CONSTRAINT ck_active_cost_nonnegative CHECK (
        cost_per_gram IS NULL OR cost_per_gram >= 0
    ),
    CONSTRAINT ck_active_usage_min_nonnegative CHECK (
        usage_level_min IS NULL OR usage_level_min >= 0
    ),
    CONSTRAINT ck_active_usage_max_nonnegative CHECK (
        usage_level_max IS NULL OR usage_level_max >= 0
    ),
    CONSTRAINT ck_active_usage_range CHECK (
        usage_level_min IS NULL OR usage_level_max IS NULL
        OR usage_level_min <= usage_level_max
    )
);

-- ============================================================================
-- 3. ACTIVE <-> BENEFIT SCORES
-- ============================================================================

CREATE TABLE IF NOT EXISTS active_benefit_score (
    active_id       INTEGER NOT NULL,
    benefit_id      INTEGER NOT NULL,
    score_version   INTEGER NOT NULL DEFAULT 1,
    score            NUMERIC(5,2) NOT NULL,
    source_note      TEXT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_active_benefit_score
        PRIMARY KEY (active_id, benefit_id, score_version),

    CONSTRAINT fk_abs_active
        FOREIGN KEY (active_id)
        REFERENCES active(active_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_abs_benefit
        FOREIGN KEY (benefit_id)
        REFERENCES benefit(benefit_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT ck_abs_score_range CHECK (score >= 0 AND score <= 20),
    CONSTRAINT ck_abs_score_version CHECK (score_version >= 1)
);

COMMENT ON TABLE active_benefit_score IS
'CelRevive active-vs-benefit score matrix. score is on the supplied 0-20 scale.';

-- ============================================================================
-- 4. NEW: SKIN CONCERN <-> WEIGHTED BENEFIT MAPPING
-- ============================================================================

CREATE TABLE IF NOT EXISTS concern_benefit (
    concern_id       VARCHAR(10) NOT NULL,
    benefit_id       INTEGER NOT NULL,
    mapping_version  INTEGER NOT NULL DEFAULT 1,
    weight           NUMERIC(6,5) NOT NULL,
    relevance_type   VARCHAR(20),
    evidence_level   VARCHAR(20) NOT NULL DEFAULT 'HYPOTHESIS',
    rationale        TEXT,
    approved_by      VARCHAR(255),
    approved_at      TIMESTAMPTZ,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_concern_benefit
        PRIMARY KEY (concern_id, benefit_id, mapping_version),

    CONSTRAINT fk_cb_concern
        FOREIGN KEY (concern_id)
        REFERENCES skin_concern(concern_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_cb_benefit
        FOREIGN KEY (benefit_id)
        REFERENCES benefit(benefit_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT ck_cb_weight CHECK (weight > 0 AND weight <= 1),
    CONSTRAINT ck_cb_mapping_version CHECK (mapping_version >= 1),
    CONSTRAINT ck_cb_relevance_type CHECK (
        relevance_type IS NULL
        OR relevance_type IN ('PRIMARY', 'SECONDARY', 'SUPPORTING')
    ),
    CONSTRAINT ck_cb_evidence_level CHECK (
        evidence_level IN ('HYPOTHESIS', 'EXPERT', 'VALIDATED')
    ),
    CONSTRAINT ck_cb_approval_consistency CHECK (
        (approved_at IS NULL)
        OR (approved_by IS NOT NULL)
    )
);

COMMENT ON TABLE concern_benefit IS
'Weighted, versioned mapping from skin concerns to CelRevive benefits. Initial Anodiam mappings should use evidence_level=HYPOTHESIS until domain approval.';

COMMENT ON COLUMN concern_benefit.weight IS
'Importance of the benefit for the concern within this mapping version. '
'All weights for one concern/version must sum to 1.00000.';

-- Aggregate weight validation cannot be expressed with a row-level CHECK.
-- Use a deferred constraint trigger so multi-row inserts/updates can be made
-- within one transaction and are validated at transaction completion.
CREATE OR REPLACE FUNCTION validate_concern_benefit_weight_sum()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_weight_sum NUMERIC(12,8);
    v_row_count  INTEGER;
BEGIN
    -- Validate the OLD concern/version group for DELETE and for UPDATEs that
    -- move a row between concern/version groups.
    IF TG_OP IN ('DELETE', 'UPDATE') THEN
        SELECT COUNT(*), COALESCE(SUM(weight), 0)
          INTO v_row_count, v_weight_sum
          FROM concern_benefit
         WHERE concern_id = OLD.concern_id
           AND mapping_version = OLD.mapping_version;

        IF v_row_count > 0
           AND ABS(v_weight_sum - 1.00000) > 0.00001 THEN
            RAISE EXCEPTION
                'concern_benefit weights must sum to 1.00000. concern_id=%, mapping_version=%, current_sum=%',
                OLD.concern_id, OLD.mapping_version, v_weight_sum;
        END IF;
    END IF;

    -- Validate the NEW concern/version group for INSERT and UPDATE.
    IF TG_OP IN ('INSERT', 'UPDATE') THEN
        SELECT COUNT(*), COALESCE(SUM(weight), 0)
          INTO v_row_count, v_weight_sum
          FROM concern_benefit
         WHERE concern_id = NEW.concern_id
           AND mapping_version = NEW.mapping_version;

        IF v_row_count > 0
           AND ABS(v_weight_sum - 1.00000) > 0.00001 THEN
            RAISE EXCEPTION
                'concern_benefit weights must sum to 1.00000. concern_id=%, mapping_version=%, current_sum=%',
                NEW.concern_id, NEW.mapping_version, v_weight_sum;
        END IF;
    END IF;

    RETURN NULL;
END;
$$;

DROP TRIGGER IF EXISTS trg_validate_concern_benefit_weight_sum ON concern_benefit;

CREATE CONSTRAINT TRIGGER trg_validate_concern_benefit_weight_sum
AFTER INSERT OR UPDATE OR DELETE ON concern_benefit
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION validate_concern_benefit_weight_sum();

-- ============================================================================
-- 5. DOCUMENT / TAG / COMPATIBILITY RELATIONSHIPS
-- ============================================================================

CREATE TABLE IF NOT EXISTS active_source_document (
    active_id       INTEGER NOT NULL,
    doc_id          BIGINT NOT NULL,
    relevance_note  TEXT,

    CONSTRAINT pk_active_source_document PRIMARY KEY (active_id, doc_id),
    CONSTRAINT fk_asd_active FOREIGN KEY (active_id)
        REFERENCES active(active_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_asd_document FOREIGN KEY (doc_id)
        REFERENCES source_document(doc_id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS active_tag (
    active_id      INTEGER NOT NULL,
    tag_id         BIGINT NOT NULL,

    CONSTRAINT pk_active_tag PRIMARY KEY (active_id, tag_id),
    CONSTRAINT fk_at_active FOREIGN KEY (active_id)
        REFERENCES active(active_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_at_tag FOREIGN KEY (tag_id)
        REFERENCES tag(tag_id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS active_incompatibility (
    active_id_low    INTEGER NOT NULL,
    active_id_high   INTEGER NOT NULL,
    is_compatible    BOOLEAN NOT NULL DEFAULT FALSE,
    note             TEXT,
    severity_level   VARCHAR(50),

    CONSTRAINT pk_active_incompatibility PRIMARY KEY (active_id_low, active_id_high),
    CONSTRAINT fk_ai_low FOREIGN KEY (active_id_low)
        REFERENCES active(active_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_ai_high FOREIGN KEY (active_id_high)
        REFERENCES active(active_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT ck_ai_distinct CHECK (active_id_low < active_id_high)
);

CREATE TABLE IF NOT EXISTS base_active_compatibility (
    base_id         BIGINT NOT NULL,
    active_id       INTEGER NOT NULL,
    is_compatible   BOOLEAN NOT NULL,
    note            TEXT,

    CONSTRAINT pk_base_active_compatibility PRIMARY KEY (base_id, active_id),
    CONSTRAINT fk_bac_base FOREIGN KEY (base_id)
        REFERENCES base(base_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_bac_active FOREIGN KEY (active_id)
        REFERENCES active(active_id) ON UPDATE CASCADE ON DELETE CASCADE
);

-- ============================================================================
-- 6. PROPOSED OPERATIONAL EXTENSION
-- ============================================================================

CREATE TABLE IF NOT EXISTS customer_session (
    session_id       UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    consent_given    BOOLEAN NOT NULL DEFAULT FALSE,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    notes            TEXT
);

CREATE TABLE IF NOT EXISTS session_skin_concern_score (
    session_id       UUID NOT NULL,
    concern_id       VARCHAR(10) NOT NULL,
    score            NUMERIC(8,4),
    detected_by      VARCHAR(30) NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_session_skin_concern_score PRIMARY KEY (session_id, concern_id),
    CONSTRAINT fk_sscs_session FOREIGN KEY (session_id)
        REFERENCES customer_session(session_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_sscs_concern FOREIGN KEY (concern_id)
        REFERENCES skin_concern(concern_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT ck_sscs_score_nonnegative CHECK (score IS NULL OR score >= 0),
    CONSTRAINT ck_sscs_detected_by CHECK (
        detected_by IN ('SELFIE', 'QUESTIONNAIRE', 'BOTH', 'MANUAL', 'OTHER')
    )
);

CREATE TABLE IF NOT EXISTS formulation (
    formulation_id   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    session_id       UUID NOT NULL,
    base_id          BIGINT NOT NULL,
    total_cost       NUMERIC(12,4),
    explanation_text TEXT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_formulation_session FOREIGN KEY (session_id)
        REFERENCES customer_session(session_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_formulation_base FOREIGN KEY (base_id)
        REFERENCES base(base_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT ck_formulation_total_cost CHECK (
        total_cost IS NULL OR total_cost >= 0
    )
);

CREATE TABLE IF NOT EXISTS formulation_active (
    formulation_id   UUID NOT NULL,
    active_id        INTEGER NOT NULL,
    grams_per_100g   NUMERIC(10,4) NOT NULL,
    cost             NUMERIC(12,4),

    CONSTRAINT pk_formulation_active PRIMARY KEY (formulation_id, active_id),
    CONSTRAINT fk_fa_formulation FOREIGN KEY (formulation_id)
        REFERENCES formulation(formulation_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_fa_active FOREIGN KEY (active_id)
        REFERENCES active(active_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT ck_fa_grams_range CHECK (
        grams_per_100g >= 0 AND grams_per_100g <= 100
    ),
    CONSTRAINT ck_fa_cost_nonnegative CHECK (cost IS NULL OR cost >= 0)
);

CREATE TABLE IF NOT EXISTS audit_log (
    audit_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id       UUID,
    event_type       VARCHAR(100) NOT NULL,
    payload          JSONB,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_audit_session FOREIGN KEY (session_id)
        REFERENCES customer_session(session_id)
        ON UPDATE CASCADE ON DELETE SET NULL
);

-- ============================================================================
-- 7. INDEXES
-- ============================================================================

CREATE INDEX IF NOT EXISTS idx_active_supplier_id
    ON active(supplier_id);

CREATE INDEX IF NOT EXISTS idx_active_category_id
    ON active(category_id);

CREATE INDEX IF NOT EXISTS idx_abs_benefit_id
    ON active_benefit_score(benefit_id);

CREATE INDEX IF NOT EXISTS idx_abs_active_current
    ON active_benefit_score(active_id, benefit_id, score_version DESC);

CREATE INDEX IF NOT EXISTS idx_cb_benefit_id
    ON concern_benefit(benefit_id);

CREATE INDEX IF NOT EXISTS idx_cb_concern_current
    ON concern_benefit(concern_id, mapping_version DESC);

CREATE INDEX IF NOT EXISTS idx_asd_doc_id
    ON active_source_document(doc_id);

CREATE INDEX IF NOT EXISTS idx_active_tag_tag_id
    ON active_tag(tag_id);

CREATE INDEX IF NOT EXISTS idx_bac_active_id
    ON base_active_compatibility(active_id);

CREATE INDEX IF NOT EXISTS idx_sscs_concern_id
    ON session_skin_concern_score(concern_id);

CREATE INDEX IF NOT EXISTS idx_formulation_session_id
    ON formulation(session_id);

CREATE INDEX IF NOT EXISTS idx_formulation_base_id
    ON formulation(base_id);

CREATE INDEX IF NOT EXISTS idx_formulation_active_active_id
    ON formulation_active(active_id);

CREATE INDEX IF NOT EXISTS idx_audit_log_session_created
    ON audit_log(session_id, created_at DESC);

-- ============================================================================
-- 8. DERIVED RECOMMENDATION VIEWS
-- ============================================================================

-- Latest version of each concern->benefit mapping, independently per concern.
CREATE OR REPLACE VIEW vw_current_concern_benefit AS
SELECT cb.*
FROM concern_benefit cb
JOIN (
    SELECT concern_id, MAX(mapping_version) AS mapping_version
    FROM concern_benefit
    GROUP BY concern_id
) latest
  ON latest.concern_id = cb.concern_id
 AND latest.mapping_version = cb.mapping_version;

-- Latest score version for each active-benefit pair.
CREATE OR REPLACE VIEW vw_current_active_benefit_score AS
SELECT abs.*
FROM active_benefit_score abs
JOIN (
    SELECT active_id, benefit_id, MAX(score_version) AS score_version
    FROM active_benefit_score
    GROUP BY active_id, benefit_id
) latest
  ON latest.active_id = abs.active_id
 AND latest.benefit_id = abs.benefit_id
 AND latest.score_version = abs.score_version;

-- Derived Active <-> Skin Concern score.
-- No physical active_concern mapping table is required.
--
-- weighted_score_0_20:
--   SUM(weight * active_benefit_score)
--
-- relevance_score_0_100:
--   weighted_score_0_20 * 5
--
-- Missing active-benefit rows are treated as score 0 and are NOT silently
-- renormalised away.
CREATE OR REPLACE VIEW vw_active_concern_score AS
SELECT
    cb.concern_id,
    sc.concern_name,
    a.active_id,
    a.active_name,
    cb.mapping_version,
    ROUND(
        SUM(cb.weight * COALESCE(abs.score, 0))
        / NULLIF(SUM(cb.weight), 0),
        4
    ) AS weighted_score_0_20,
    ROUND(
        5 * SUM(cb.weight * COALESCE(abs.score, 0))
        / NULLIF(SUM(cb.weight), 0),
        2
    ) AS relevance_score_0_100,
    CASE MIN(
        CASE cb.evidence_level
            WHEN 'HYPOTHESIS' THEN 1
            WHEN 'EXPERT'     THEN 2
            WHEN 'VALIDATED'  THEN 3
        END
    )
        WHEN 1 THEN 'HYPOTHESIS'
        WHEN 2 THEN 'EXPERT'
        WHEN 3 THEN 'VALIDATED'
    END AS mapping_evidence_floor,
    COUNT(*) AS mapped_benefit_count
FROM vw_current_concern_benefit cb
JOIN skin_concern sc
  ON sc.concern_id = cb.concern_id
CROSS JOIN active a
LEFT JOIN vw_current_active_benefit_score abs
  ON abs.active_id = a.active_id
 AND abs.benefit_id = cb.benefit_id
GROUP BY
    cb.concern_id,
    sc.concern_name,
    a.active_id,
    a.active_name,
    cb.mapping_version;

-- Ranked recommendation view for convenient API/query consumption.
CREATE OR REPLACE VIEW vw_ranked_active_concern_score AS
SELECT
    x.*,
    DENSE_RANK() OVER (
        PARTITION BY x.concern_id
        ORDER BY x.relevance_score_0_100 DESC, x.active_id
    ) AS active_rank
FROM vw_active_concern_score x;

COMMENT ON VIEW vw_active_concern_score IS
'Derived active-to-skin-concern relevance. Do not replace with a manually maintained direct mapping table.';

COMMENT ON VIEW vw_ranked_active_concern_score IS
'Ranks all actives for each skin concern using the latest concern-benefit mapping and active-benefit scores.';

-- ============================================================================
-- 9. OPTIONAL VALIDATION / QA VIEWS
-- ============================================================================

-- Should return zero rows when all concern/version weight sets are valid.
CREATE OR REPLACE VIEW vw_invalid_concern_benefit_weight_sum AS
SELECT
    concern_id,
    mapping_version,
    SUM(weight) AS weight_sum
FROM concern_benefit
GROUP BY concern_id, mapping_version
HAVING ABS(SUM(weight) - 1.00000) > 0.00001;

-- Identifies missing active-benefit score cells for the current benefit set.
-- With 15 actives and 20 benefits, a complete matrix is expected to contain
-- 300 current active-benefit combinations.
CREATE OR REPLACE VIEW vw_missing_active_benefit_score AS
SELECT
    a.active_id,
    a.active_name,
    b.benefit_id,
    b.benefit_name
FROM active a
CROSS JOIN benefit b
LEFT JOIN vw_current_active_benefit_score abs
  ON abs.active_id = a.active_id
 AND abs.benefit_id = b.benefit_id
WHERE abs.active_id IS NULL;

COMMIT;

-- ============================================================================
-- IMPLEMENTATION / GOVERNANCE RULES (DOCUMENTATION)
-- ============================================================================
-- 1. concern_benefit is the ONLY manually curated bridge between skin concerns
--    and benefits for the recommendation model.
-- 2. Do not insert a permanent active<->skin_concern master mapping.
-- 3. Initial inferred mappings should use evidence_level='HYPOTHESIS'.
-- 4. CelRevive/domain-approved mappings should be introduced as a NEW
--    mapping_version; do not overwrite previous approved versions.
-- 5. Active-benefit score changes should similarly use a new score_version.
-- 6. Every concern/version must sum to exactly 1.00000 across its benefit weights.
-- 7. Recommendation APIs should normally query vw_ranked_active_concern_score.
-- 8. Suitability/safety/compatibility filtering is a separate stage from
--    relevance scoring and should be applied after concern relevance is derived.
-- ============================================================================
