-- ============================================================================
-- CelRevive - Allergen / Active Exclusion Migration
-- Work item: 1.1 Add exclusion table
-- Target: PostgreSQL
--
-- Purpose
--   Introduce a structured allergen/contraindication master and a junction
--   table linking allergens to active ingredients that must be excluded.
--
-- IMPORTANT
--   No allergen vocabulary or active-exclusion pairs are seeded here because
--   the current CelRevive workspace does not contain an authoritative,
--   structured allergen list or approved exclusion matrix. Those values must
--   come from the approved domain input for work item 1.4.
-- ============================================================================

BEGIN;

-- ---------------------------------------------------------------------------
-- 1. Allergen / contraindication master
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS allergen_exclusion_master (
    allergen_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    allergen_code     VARCHAR(100) NOT NULL,
    allergen_name     VARCHAR(255) NOT NULL,
    description       TEXT,
    is_active         BOOLEAN NOT NULL DEFAULT TRUE,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_allergen_exclusion_master_code UNIQUE (allergen_code),
    CONSTRAINT uq_allergen_exclusion_master_name UNIQUE (allergen_name)
);

COMMENT ON TABLE allergen_exclusion_master IS
'CelRevive structured allergen/contraindication vocabulary used by the safety/exclusion stage.';

-- ---------------------------------------------------------------------------
-- 2. Allergen -> active exclusion junction
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS active_allergen_exclusion (
    allergen_id       BIGINT NOT NULL,
    active_id         INTEGER NOT NULL,
    exclusion_reason  TEXT,
    source_note       TEXT,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_active_allergen_exclusion
        PRIMARY KEY (allergen_id, active_id),

    CONSTRAINT fk_aae_allergen
        FOREIGN KEY (allergen_id)
        REFERENCES allergen_exclusion_master(allergen_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_aae_active
        FOREIGN KEY (active_id)
        REFERENCES active(active_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

COMMENT ON TABLE active_allergen_exclusion IS
'Maps a structured allergen/contraindication to an active ingredient that must be excluded for safety/suitability.';

-- ---------------------------------------------------------------------------
-- 3. Indexes for safety filtering
-- ---------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_aae_active_id
    ON active_allergen_exclusion(active_id);

CREATE INDEX IF NOT EXISTS idx_aae_allergen_id
    ON active_allergen_exclusion(allergen_id);

-- ---------------------------------------------------------------------------
-- 4. QA helper view: configured exclusion mappings
-- ---------------------------------------------------------------------------
CREATE OR REPLACE VIEW vw_active_allergen_exclusion_review AS
SELECT
    aae.allergen_id,
    aem.allergen_code,
    aem.allergen_name,
    aae.active_id,
    a.active_name,
    aem.is_active AS allergen_is_active,
    aae.exclusion_reason,
    aae.source_note
FROM active_allergen_exclusion aae
JOIN allergen_exclusion_master aem
  ON aem.allergen_id = aae.allergen_id
JOIN active a
  ON a.active_id = aae.active_id;

COMMIT;

-- ============================================================================
-- Post-migration verification
-- ============================================================================
-- SELECT * FROM allergen_exclusion_master ORDER BY allergen_id;
-- SELECT * FROM active_allergen_exclusion ORDER BY allergen_id, active_id;
-- SELECT * FROM vw_active_allergen_exclusion_review;
-- ============================================================================


--===========
--VERIFY    =
--===========
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
  AND table_name IN (
      'allergen_exclusion_master',
      'active_allergen_exclusion'
  )
ORDER BY table_name;



SELECT COUNT(*) AS active_count
FROM active;

SELECT COUNT(*) AS allergen_count
FROM allergen_exclusion_master;



